name: ayna
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  go_router: ^13.0.1
  video_player: ^2.8.2
  gif_view: ^0.4.0
  path_provider: ^2.1.2
  bloc_test: ^9.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  hive_generator: ^2.0.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
